import type { ReactNode } from 'react';
import Link from 'next/link';
import { siteConfig, pagePath, type Locale, type PageKind } from '../lib/site-config';
const days = siteConfig.deletionResponseDays;
export type PolicySection = { id: string; title: string; content: ReactNode };
export type PolicyContent = { title: string; intro: string; sections: PolicySection[] };
export function Contact({ locale }: { locale: Locale }) {
  return siteConfig.supportEmail ? <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a> : <span className="pending-detail">{locale === 'en' ? '[Public support email — to be added]' : '[公共联系邮箱 — 待填写]'}</span>;
}
export function contentFor(kind: PageKind, locale: Locale): PolicyContent {
  const zh = locale === 'zh';
  const contact = <Contact locale={locale} />;
  const privacy = <Link href={pagePath('privacy', locale)}>{zh ? '隐私政策' : 'Privacy policy'}</Link>;
  const support = <Link href={pagePath('support', locale)}>{zh ? '帮助与联系' : 'Support'}</Link>;
  const deletion = <Link href="/">{zh ? '删除账号页面' : 'account deletion page'}</Link>;
  const operator = siteConfig.operatorName || (zh ? '[运营者名称 — 待填写]' : '[Operator name — to be added]');
  if (kind === 'privacy') return {
    title: zh ? '隐私政策' : 'Privacy policy',
    intro: zh ? '本政策说明 Little Sign 应用和配套网站如何处理你的信息，以及你如何管理和删除信息。' : 'This policy explains how the Little Sign app and its companion website handle your information, and how you can manage or delete it.',
    sections: [
      { id: 'operator', title: zh ? '1. 运营者与联系' : '1. Operator and contact', content: <><p>{zh ? `Little Sign 的运营者为 ${operator}。` : `Little Sign is operated by ${operator}.`}</p><p>{zh ? '隐私问题、数据请求或疑似儿童数据，请联系：' : 'For privacy questions, data requests, or concerns about children’s information, contact: '}{contact}.</p></> },
      { id: 'device', title: zh ? '2. 保存在设备上的内容' : '2. Information on your device', content: <>
        <p>{zh ? '每日卡牌、笔记、意图、已保存的解读、决定与状态、轮盘选项、心情与使用信号、主题和语言设置保存在设备上。应用生成一个本地安装标识，使抽牌结果保持一致；它不是广告标识。无需创建账号即可使用访客核心功能。' : 'Daily cards, notes, intentions, saved readings, decisions and their status, wheel options, mood and usage signals, themes, and language preferences are stored on your device. A local installation identifier helps keep draws consistent; it is not an advertising ID. Core guest features do not require an account.'}</p>
        <p>{zh ? '这些本地记录不会自动同步到我们的服务器。当前版本没有云端日记备份。我们不使用广告或分析 SDK 来上传这些记录。不要仅凭退出账号就认为设备数据已清除。' : 'These local records do not automatically sync to our servers. The current release has no cloud journal backup. We do not use advertising or analytics SDKs to upload these records. Signing out does not erase device data.'}</p>
      </> },
      { id: 'accounts', title: zh ? '3. 邮箱账号与服务记录' : '3. Email accounts and service records', content: <>
        <p>{zh ? '当你注册或登录时，Supabase 及验证码邮件服务会处理你的邮箱、验证码验证、账号标识和登录会话，以验证身份并提供需要登录的功能。登录会话保存在设备上；验证码不会保存到日记中。' : 'When you register or sign in, Supabase and the verification-email delivery service process your email address, code verification, account identifier, and sign-in sessions to verify identity and provide account features. Sign-in sessions are stored on your device; verification codes are not saved in your journal.'}</p>
        <p>{zh ? '我们在服务器保存与账号关联的 AI 请求日期和次数，以执行使用限制并控制滥用。这些计数不包含你的问题、答案或笔记。' : 'We keep an account-linked AI request date and count on the server to enforce usage limits and control abuse. Those counters do not contain your question, answer, or notes.'}</p>
      </> },
      { id: 'ai', title: zh ? '4. 可选 AI 问题' : '4. Optional AI questions', content: <>
        <p>{zh ? '当你明确提交自定义 AI 问题时，你输入的问题、可选背景和所抽卡牌的信息会经由我们的 Supabase 服务发送给 DeepSeek 生成解读。问题中可能包含你自行输入的个人信息，请不要填写你不希望被处理的敏感信息或他人的私人信息。' : 'When you explicitly submit a custom AI question, your question, optional context, and drawn-card information pass through our Supabase service to DeepSeek to generate a reading. Your text may include personal information you choose to enter. Avoid sensitive information you do not want processed and other people’s private information.'}</p>
        <p>{zh ? '我们不会把邮箱、账号标识、私人笔记、历史记录或心情信号加入 AI 提示词。账号仍用于在我们的服务上验证请求。答案返回应用，只有当你选择保存时才会写入本地历史。应用后端不会将问题和答案写入日记数据库，也没有主动记录问题正文的日志。服务商的运行日志、保留与处理可能独立于此流程。' : 'We do not include your email, account ID, private notes, history, or mood signals in the AI prompt. Your account still authenticates the request to our service. The answer returns to the app and is written to local history only when you choose to save it. The app backend does not store questions and answers in a journal database or deliberately log question bodies. Provider operational logging, retention, and processing can be separate from this flow.'}</p>
        <p>{zh ? '我们不将你的本地日记用于训练 AI。本政策不承诺 AI 服务商对已提交文本提供零保留或不用于训练的处理；这些条件需以适用的 API 服务协议和已配置的设置为准。你可以不使用 AI，继续使用离线卡牌和预设情景。' : 'We do not use your local journal to train AI. This policy does not promise zero retention or no training by the AI provider for submitted text; those conditions depend on the applicable API agreement and configured settings. You can avoid AI processing and continue using offline cards and authored scenarios.'}</p>
      </> },
      { id: 'sharing', title: zh ? '5. 分享、照片与设备权限' : '5. Sharing, photos, and device permissions', content: <>
        <p>{zh ? '当你主动导出或分享卡牌时，应用会创建图片并将它交给你选择的系统分享应用，或保存到照片库。当前卡牌分享排除私人笔记、意图和自定义问题。接收方及你选择的应用会按自己的规则处理已分享的图片。' : 'When you choose to export or share a card, the app creates an image and passes it to the system sharing app you select, or saves it to your photo library. Current card sharing excludes private notes, intentions, and custom questions. Recipients and the apps you choose handle the shared image under their own rules.'}</p>
        <p>{zh ? '保存图片时，旧版 Android 可能请求存储权限，iOS 可能请求添加照片的权限。应用不需要读取整个照片库，也不通过核心功能收集联系人、精确位置、摄像头或麦克风内容。你可以在系统设置中管理权限。' : 'Saving an image may require storage permission on older Android versions or permission to add photos on iOS. The app does not need to read your entire photo library, and its core features do not collect contacts, precise location, camera, or microphone content. Manage permissions in your device settings.'}</p>
      </> },
      { id: 'providers', title: zh ? '6. 服务商、网站与网络信息' : '6. Providers, website, and network information', content: <>
        <p>{zh ? 'Supabase 提供身份验证、数据库和应用后端。邮件服务负责发送验证码。DeepSeek 处理你提交的 AI 问题。网站通过 GitHub Pages 托管。网络服务商会收到处理连接所需的 IP 地址等网络信息，并可能处理请求时间、浏览器或设备信息和安全日志，用于运行、保护和诊断服务。' : 'Supabase provides authentication, the database, and the app backend. Email delivery services send verification codes. DeepSeek processes submitted AI questions. GitHub Pages hosts this website. Network providers receive information such as your IP address needed to handle connections, and may process request times, browser or device information, and security logs to run, secure, and diagnose services.'}</p>
        <p>{zh ? '网站本身不设置 Cookie，也不在浏览器中保存数据；删除申请页只会打开你的邮件应用并预填内容，网站不会自行发送任何信息。网站没有添加广告或营销跟踪。托管平台可能使用其自身的安全或访问控制 Cookie。通过邮件联系我们时，你的邮箱和所提供内容会由邮件服务处理。' : 'The website sets no cookies of its own and stores nothing in your browser; the deletion request page only opens your email app with a prefilled message and sends nothing itself. The website adds no advertising or marketing tracking. The hosting platform may use its own security or access-control cookies. If you email us, email services process your address and the content you provide.'}</p>
        <p>{zh ? '我们不出售个人信息。除提供服务的服务商、你主动选择的分享接收方，以及法律要求或保护服务安全所必需的披露外，我们不会主动披露你的记录。处理可能发生在你所在国家以外。有关服务商的说明：' : 'We do not sell personal information. We do not deliberately disclose your records except to providers delivering the service, recipients you choose when sharing, or where necessary for legal requirements or service security. Processing may occur outside your country. Provider information: '}
          <a href="https://supabase.com/privacy">Supabase</a>{' · '}<a href="https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html">DeepSeek</a>{' · '}<a href="https://docs.github.com/site-policy/privacy-policies/github-general-privacy-statement">GitHub</a>.</p>
        <p>{zh ? '服务商面向自身用户的隐私政策不一定覆盖通过 API 提交的数据；Little Sign 的本政策及适用的服务协议共同说明相应处理。' : 'A provider’s policy for its own users may not cover data submitted through an API; this Little Sign policy and the applicable service agreements govern the corresponding processing.'}</p>
      </> },
      { id: 'retention', title: zh ? '7. 保留与删除' : '7. Retention and deletion', content: <>
        <ul>
          <li>{zh ? '本地记录保留到你删除记录或使用设置中的“清除本机数据”。卸载、设备丢失或重置也可能导致记录丢失；导出的图片和其他副本需要另外删除。' : 'Local records remain until you delete them or use Settings → Clear my data on this device. Uninstalling, losing, or resetting a device can also cause data loss; exported images and other copies must be deleted separately.'}</li>
          <li>{zh ? '账号记录保留到你删除账号。你可以在应用设置中使用“删除账号”，或按照' : 'Account records remain until you delete the account. Use Settings → Delete my account in the app, or email a request as described on the '}{deletion}{zh ? `的说明通过邮件申请。应用内删除经验证和确认后立即执行；邮件申请以发件邮箱核实归属，我们在收到可核实请求后 ${days} 天内完成并回信确认。两种方式都会删除账号、关联登录记录及每个账号的使用计数，并通过已部署的数据关系删除其他关联记录。退出登录或清除本机数据不会删除账号。` : `. In-app deletion runs immediately after verification and confirmation; an email request is verified by the sending address and completed within ${days} days of a verifiable request, with a confirmation reply. Both remove the account, linked sign-in records, per-account usage counts, and other linked records covered by the deployed data relationships. Signing out or clearing this device does not delete the account.`}</li>
          <li>{zh ? '从应用删除账号时，该设备上可识别为属于该账号的 AI 历史会被删除。访客记录、旧版未归属记录和其他账号记录保留。我们无法擦除任何设备上的本地副本；请在每台设备上分别清除数据。' : 'Deleting an account from the app removes identifiable AI history belonging to that account on that device. Guest records, older unowned records, and other accounts’ records remain. We cannot erase local copies on any device; clear data on each device separately.'}</li>
          <li>{zh ? '使用计数在新一天请求时重置；成功处理请求时会清理超过两个日历日的旧计数。此清理由请求触发，并非定时保证。删除账号会移除其计数；不包含账号标识的全局计数保留。' : 'Usage counts reset on a request on a new day; successful request processing removes counts older than two calendar days. Cleanup is request-triggered, not a timed guarantee. Account deletion removes its count; the global count without account identifiers remains.'}</li>
          <li>{zh ? '服务商日志、备份及已发送的 AI 文本可能按适用协议继续保留，用于安全、滥用防护、服务运行或法律义务。即时账号删除不保证抹除这些副本。有关适用于你请求的保留期限或删除协助，请联系下方邮箱。我们不为追踪删除而创建新的服务器账号记录。' : 'Provider logs, backups, and submitted AI text may remain under applicable agreements for security, abuse prevention, service operation, or legal obligations. Immediate account deletion does not guarantee erasure of those copies. Contact us below for the retention periods applicable to your request or deletion assistance. We create no new server account record to track deletion.'}</li>
        </ul>
      </> },
      { id: 'security-rights', title: zh ? '8. 安全、选择与权利' : '8. Security, choices, and rights', content: <>
        <p>{zh ? '账号和 AI 请求通过 HTTPS 传输。后端验证账号权限，管理密钥不会放入应用或网页。本地存储依赖设备和应用沙盒保护，并不提供独立的加密日记保险箱。请保护设备和邮箱；没有任何系统能保证绝对安全。' : 'Account and AI requests use HTTPS. The backend verifies account authorization, and administrative keys are not included in the app or website. Local storage relies on device and app-sandbox protection; it is not a separately encrypted journal vault. Protect your device and email account; no system guarantees absolute security.'}</p>
        <p>{zh ? '你可以使用访客模式、选择不提交 AI 问题、退出账号、管理权限、删除本地记录或申请删除账号。根据所在地法律，你还可能享有访问、更正、获取副本、删除、限制处理、反对处理或撤回同意等权利，以及向监管机构投诉的权利。我们可能需要验证身份；不会要求你发送验证码或密码。' : 'You can use guest mode, avoid submitting AI questions, sign out, manage permissions, delete local records, or request account deletion. Depending on your location, you may also have rights to access, correct, receive a copy of, delete, restrict or object to processing of your data, withdraw consent, and complain to a regulator. We may need to verify identity; we will not ask you to send a verification code or password.'}</p>
        <p>{zh ? '行使权利或请求帮助：' : 'For a rights request or assistance: '}{contact}. {support}.</p>
      </> },
      { id: 'children-changes', title: zh ? '9. 儿童与政策更新' : '9. Children and policy updates', content: <>
        <p>{zh ? 'Little Sign 提供日常反思，不以儿童为目标。如果你认为儿童提供了个人信息，请联系运营者，我们会调查并按适用法律处理。' : 'Little Sign offers everyday reflection and is not directed at children. If you believe a child has supplied personal information, contact the operator so we can investigate and handle it under applicable law.'}</p>
        <p>{zh ? '本页会注明更新日期。重要处理方式变化将通过应用或其他适当渠道告知；需要同意时会另外征求同意。' : 'This page shows its update date. Material changes to data handling will be communicated through the app or another appropriate channel; consent will be requested separately where required.'}</p>
      </> },
    ],
  };
  if (kind === 'terms') return {
    title: zh ? '服务条款' : 'Terms of service',
    intro: zh ? '以下条款说明 Little Sign 的使用方式、内容限制和你对数据的选择。' : 'These terms explain use of Little Sign, the limits of its content, and your choices about your data.',
    sections: [
      { id: 'service', title: zh ? '1. 服务与运营者' : '1. Service and operator', content: <><p>{zh ? `Little Sign 由 ${operator} 运营，提供卡牌反思、日常决定提示及可选的 AI 解读。使用服务时，请遵守本条款及适用法律。如果你尚未达到当地独立订立协议的年龄，请在法律要求时获得父母或监护人许可。` : `Little Sign is operated by ${operator} and offers card-based reflection, everyday decision prompts, and optional AI readings. Use the service in accordance with these terms and applicable law. If you are below the age to enter an agreement independently where you live, obtain parental or guardian permission where the law requires it.`}</p><p>{zh ? '联系方式：' : 'Contact: '}{contact}.</p></> },
      { id: 'reflection', title: zh ? '2. 反思工具与 AI 局限' : '2. Reflection and AI limitations', content: <><p>{zh ? '卡牌和解读是反思提示，不预测未来，也不保证任何结果。AI 内容可能错误、偏颇、不完整或不适合你的情况。你有权拒绝建议，并对自己的选择负责。' : 'Cards and readings are prompts for reflection. They do not predict the future or guarantee an outcome. AI content may be incorrect, biased, incomplete, or unsuitable for your circumstances. You may reject any suggestion and remain responsible for your choices.'}</p><p>{zh ? '不要把 Little Sign 当作医疗、心理健康、法律、财务或其他专业意见，也不要用它处理紧急或高风险决定。遇到紧急危险时，请联系当地紧急服务或合适的专业人士。' : 'Do not rely on Little Sign as medical, mental-health, legal, financial, or other professional advice, or use it for emergency or high-stakes decisions. For immediate danger, contact local emergency services or an appropriate professional.'}</p></> },
      { id: 'account', title: zh ? '3. 账号与使用' : '3. Accounts and use', content: <><p>{zh ? '核心离线功能可以使用访客模式。新 AI 解读需要验证邮箱的账号、网络连接和可用的服务额度。请使用你有权访问的邮箱，并保护你的登录方式。不要共享验证码、绕过限制、干扰服务、尝试访问其他人的账号，或提交违法、有害内容或未经授权的私人信息。' : 'Core offline features work in guest mode. New AI readings require an email-verified account, connectivity, and available service capacity. Use an email address you are entitled to access and protect your sign-in methods. Do not share verification codes, bypass limits, disrupt the service, try to access another person’s account, or submit unlawful or harmful content or private information without authorization.'}</p><p>{zh ? '我们可以拒绝不支持的请求，并在保护服务或履行法律义务所必要时限制访问。服务额度、卡牌和功能可能变化；需要网络的功能可能中断。' : 'We may decline unsupported requests and restrict access where necessary to protect the service or meet legal obligations. Service limits, cards, and features may change; network features can be interrupted.'}</p></> },
      { id: 'content', title: zh ? '4. 你的内容与应用内容' : '4. Your content and app content', content: <><p>{zh ? '你的问题和笔记仍属于你。提交 AI 问题时，你允许我们及服务商为处理该请求所必需而处理输入。我们不因此获得你本地日记的所有权。数据处理见' : 'Your questions and notes remain yours. When you submit an AI question, you permit us and our providers to process the input as needed to handle that request. We do not acquire ownership of your local journal. Data handling is explained in the '}{privacy}.</p><p>{zh ? '应用设计、文字、卡牌艺术及软件受相应权利保护。你可以按应用提供的功能使用和分享卡牌图片；这不转让底层作品的所有权。不要冒充运营者、声称官方背书，或侵害他人权利。第三方字体和软件许可仍适用。' : 'App design, text, card artwork, and software remain subject to their respective rights. You may use and share card images through the app’s provided features; this does not transfer ownership of the underlying works. Do not impersonate the operator, imply official endorsement, or infringe others’ rights. Third-party font and software licenses continue to apply.'}</p></> },
      { id: 'data-exit', title: zh ? '5. 保存、离开与删除' : '5. Storage, leaving, and deletion', content: <><p>{zh ? '当前版本没有云端日记备份。设备丢失、清除应用数据或卸载可能使本地记录无法恢复。请在删除前保存你需要的内容。退出登录只退出当前设备，账号仍然存在。' : 'The current release has no cloud journal backup. Losing a device, clearing app data, or uninstalling may make local records unrecoverable. Save anything you need before deleting. Signing out only signs out this device; your account remains.'}</p><p>{zh ? '你可以停止使用，并在设置中删除账号或使用' : 'You may stop using the service and delete your account in Settings or through the '}{deletion}{zh ? '。保留范围、其他设备副本和删除说明见' : '. For retention, other-device copies, and deletion scope, read the '}{privacy}.</p></> },
      { id: 'payments', title: zh ? '6. 费用与第三方服务' : '6. Payments and third-party services', content: <><p>{zh ? '当前版本没有应用内付费订阅或购买流程。如果将来提供付费功能，价格、续订、取消和适用商店条款将在购买前显示。你的网络服务商可能收取流量费用。' : 'The current release has no in-app paid subscription or purchase flow. If paid features are introduced, pricing, renewal, cancellation, and applicable store terms will be shown before purchase. Your network provider may charge for data use.'}</p><p>{zh ? '你选择的邮件、分享或其他第三方服务由其自身运营。你访问它们时，可能需要遵守其条款。' : 'Email, sharing, and other third-party services you choose are operated separately. Their terms may apply when you use them.'}</p></> },
      { id: 'rights-changes', title: zh ? '7. 法定权利、更新与帮助' : '7. Legal rights, updates, and help', content: <><p>{zh ? '我们不保证服务始终可用、没有错误或 AI 输出适合某个目的。本条款不排除或限制适用法律不能排除的消费者权利或责任。' : 'We do not promise uninterrupted or error-free service, or that AI output is suitable for a particular purpose. These terms do not exclude or limit consumer rights or responsibilities that applicable law does not allow to be excluded.'}</p><p>{zh ? '本页注明更新日期。重要条款变化将通过适当方式通知；需要接受时会另行征求。疑问或有问题的内容，请前往' : 'This page shows its update date. Material changes will be communicated appropriately, with acceptance requested where required. For questions or problematic content, visit '}{support}{zh ? '或联系 ' : ' or contact '}{contact}.</p></> },
    ],
  };
  return {
    title: zh ? '帮助与联系' : 'Support',
    intro: zh ? '获取登录、数据管理和 Little Sign 使用方面的帮助。' : 'Get help with sign-in, your data, and using Little Sign.',
    sections: [
      { id: 'contact', title: zh ? '联系 Little Sign' : 'Contact Little Sign', content: <><p>{zh ? '应用问题、隐私请求或不适当解读，请联系：' : 'For app problems, privacy requests, or an inappropriate reading, contact: '}{contact}.</p><p>{zh ? '请说明应用版本、设备系统、问题发生时间及重现步骤。只发送解决问题所必需的信息。截图请先移除私人笔记和邮箱；不要发送验证码、密码或其他人的私人信息。' : 'Include the app version, device operating system, when the problem happened, and steps to reproduce it. Share only what is needed to resolve the issue. Remove private notes and email addresses from screenshots; never send verification codes, passwords, or someone else’s private information.'}</p></> },
      { id: 'signin', title: zh ? '收不到验证码或无法登录' : 'Missing codes or sign-in trouble', content: <><p>{zh ? '检查邮箱拼写和垃圾邮件，等待重新发送倒计时结束，使用最新的验证码。登录现有账号不会自动注册；新用户请在应用中明确选择创建账号。' : 'Check the email spelling and spam folder, wait for the resend countdown, and use the newest code. Signing in does not automatically register an account; new users should explicitly choose Create an account in the app.'}</p><p>{zh ? '网络或邮件服务不可用时，可以返回访客模式继续使用离线功能。无需把验证码发给我们。' : 'If the network or email service is unavailable, return to guest mode for offline features. You do not need to send us your code.'}</p></> },
      { id: 'delete', title: zh ? '删除账号或设备数据' : 'Delete an account or device data', content: <><p>{zh ? '要永久删除账号，请在应用设置选择“删除账号”，或按照' : 'To permanently delete an account, choose Delete my account in app Settings, or follow the '}{deletion}{zh ? `的说明，用账号邮箱发送申请。应用内删除需要验证身份并确认；邮件申请以发件邮箱核实，我们在 ${days} 天内完成并回信确认。清除本机数据是不同的操作：它删除这台设备上的记录并退出登录，但账号仍然存在。` : ` and email the request from your account address. In-app deletion requires identity verification and confirmation; an email request is verified by the sending address and completed within ${days} days, with a confirmation reply. Clear my data on this device is a separate action: it removes this device’s records and signs you out, but leaves the account intact.`}</p><p>{zh ? '如果应用内删除后连接中断，请使用“查看并重试删除”，不要因为未收到回复就假定删除失败。无法访问邮箱时请联系支持，我们需要确认所有权，不能仅凭一个账号地址删除他人的信息。' : 'If the in-app connection drops after deletion was sent, use Check and retry deletion; lack of a response does not prove failure. If you cannot access your email, contact support; we need to establish ownership and cannot delete someone’s information based only on an account address.'}</p></> },
      { id: 'offline', title: zh ? '离线内容与已保存记录' : 'Offline content and saved records', content: <><p>{zh ? '每日卡牌和预设情景可以离线使用。生成新的 AI 解读需要网络及已验证账号。已保存的 AI 解读留在生成它们的设备上；退出登录会隐藏账号专属记录，再次登录同一账号可恢复查看。本版本没有跨设备日记同步。' : 'Daily cards and authored scenarios work offline. Generating a new AI reading requires connectivity and a verified account. Saved AI readings stay on the device where they were saved; signing out hides account-owned entries, and signing back into the same account restores access. This release has no cross-device journal sync.'}</p></> },
      { id: 'report', title: zh ? '报告不适当的 AI 解读' : 'Report an inappropriate AI reading', content: <><p>{zh ? '你可以不采纳或不保存任何解读。请通过上方支持邮箱说明问题、发生时间及你愿意提供的相关片段。报告可能涉及敏感信息，仅提供必要内容，并说明是否希望删除已提供的报告内容。' : 'You can reject or avoid saving any reading. Use the support email above to describe the concern, when it happened, and any relevant excerpt you choose to share. Reports can contain sensitive information; include only what is needed and tell us if you want the supplied report content deleted.'}</p><p>{zh ? '支持邮箱不是紧急服务。若有人处于即时危险中，请联系当地紧急服务。' : 'The support inbox is not an emergency service. If someone is in immediate danger, contact local emergency services.'}</p></> },
      { id: 'policies', title: zh ? '政策与条款' : 'Policies and terms', content: <p>{privacy}{' · '}<Link href={pagePath('terms', locale)}>{zh ? '服务条款' : 'Terms of service'}</Link>{' · '}{deletion}</p> },
    ],
  };
}
